server:
  port: 8002
  context-path: /ui
  session:
    cookie:
      name: UISESSION
      
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: ClientId
      client-secret: secret
      accessTokenUri: http://localhost:8001/auth/oauth/token
      user-authorization-uri: http://localhost:8001/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8001/auth/rest/users/principal
      
logging:
  level:
    root: DEBUG